# Hydrogen
spacing = 10
padding = 0
hide_ascii = true
key_color = "Green"
separator = ""

[bar]
glyph = ""
hide_delimiters = true
visible = true

[palette]
type = "Full"
glyph = "  "
visible = true
[box]
border = "rounded"
visible = true
title = "─Jack-Frings"

[box.inner_margin]
x = 1
y = 0

[keys]
host = "Host"
battery = "Battery"
distro = "Distro"
uptime = "Uptime"
memory = "Memory"
backlight = "Brightness"
